//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigTkOnBehalfOf
    {
        public int IdConfig { get; set; }
        public int IdUserOnBehalfOf { get; set; }
        public int IdUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
