//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSettingsPriority
    {
        public int IdSetting { get; set; }
        public int IdPriority { get; set; }
    
        public virtual NotificationSettings NotificationSettings { get; set; }
    }
}
