//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSettings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotificationSettings()
        {
            this.NotificationSettingsPriority = new HashSet<NotificationSettingsPriority>();
            this.NotificationSettingsStatus = new HashSet<NotificationSettingsStatus>();
        }
    
        public int IdSetting { get; set; }
        public bool SendResponsable { get; set; }
        public bool SendColaborator { get; set; }
        public bool SendFollower { get; set; }
        public bool SendAddComment { get; set; }
        public bool SendEditComment { get; set; }
        public int IdUser { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationSettingsPriority> NotificationSettingsPriority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationSettingsStatus> NotificationSettingsStatus { get; set; }
    }
}
