//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonTask
    {
        public int IdTask { get; set; }
        public int IdPerson { get; set; }
        public bool Iscolaborator { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Task Task { get; set; }
    }
}
