//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonContact
    {
        public int IdContact { get; set; }
        public int IdPerson { get; set; }
        public int IdPhoneNumberType { get; set; }
        public string IdIsoCountry { get; set; }
        public string PhoneNumber { get; set; }
        public bool Status { get; set; }
    
        public virtual CatalogDetail CatalogDetail { get; set; }
        public virtual Country Country { get; set; }
        public virtual Person Person { get; set; }
    }
}
