//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonContact
    {
        public int IdContact { get; set; }
        public int IdPerson { get; set; }
        public int IdPhoneNumberType { get; set; }
        public string IdIsoCountry { get; set; }
        public string PhoneNumber { get; set; }
        public bool Status { get; set; }
    
        public virtual CatalogDetail CatalogDetail { get; set; }
        public virtual Country Country { get; set; }
        public virtual Person Person { get; set; }
    }
}
