//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAcces
    {
        public int IdRole { get; set; }
        public int IdOption { get; set; }
        public bool Visible { get; set; }
        public bool Create { get; set; }
        public bool Search { get; set; }
        public bool Edit { get; set; }
        public bool Delete { get; set; }
    
        public virtual OptionMenu OptionMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
