//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAcces
    {
        public int IdRole { get; set; }
        public int IdOption { get; set; }
        public bool Visible { get; set; }
        public bool Create { get; set; }
        public bool Search { get; set; }
        public bool Edit { get; set; }
        public bool Delete { get; set; }
    
        public virtual OptionMenu OptionMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
