//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestAssets
    {
        public int IdAsset { get; set; }
        public int IdServiceRequest { get; set; }
        public int IdAssetsType { get; set; }
        public string Description { get; set; }
        public string Beneficiaries { get; set; }
        public string Administrators { get; set; }
    
        public virtual CatalogDetail CatalogDetail { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
