//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestAssets
    {
        public int IdAsset { get; set; }
        public int IdServiceRequest { get; set; }
        public int IdAssetsType { get; set; }
        public string Description { get; set; }
        public string Beneficiaries { get; set; }
        public string Administrators { get; set; }
    
        public virtual CatalogDetail CatalogDetail { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
