//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.CatalogDetail4 = new HashSet<CatalogDetail>();
            this.Task = new HashSet<Task>();
        }
    
        public int IdServiceRequest { get; set; }
        public int IdServiceType { get; set; }
        public int IdServiceStatus { get; set; }
        public int IdPerson { get; set; }
        public Nullable<int> IdContactType { get; set; }
        public Nullable<int> IdPropertyType { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> DownPayment { get; set; }
        public Nullable<decimal> ClosingCost { get; set; }
        public Nullable<decimal> MonthlyIncome { get; set; }
        public Nullable<decimal> DebtPayment { get; set; }
        public Nullable<decimal> Piti { get; set; }
        public Nullable<decimal> Ratios { get; set; }
        public Nullable<decimal> EstimatedValue { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> CurrentDebt { get; set; }
        public string Assets { get; set; }
        public string Beneficiaries { get; set; }
        public string Process { get; set; }
        public string Wish { get; set; }
        public Nullable<bool> Plane { get; set; }
        public Nullable<bool> Financing { get; set; }
        public string Note { get; set; }
        public int IdUser { get; set; }
        public string RegisterUser { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual CatalogDetail CatalogDetail { get; set; }
        public virtual CatalogDetail CatalogDetail1 { get; set; }
        public virtual CatalogDetail CatalogDetail2 { get; set; }
        public virtual CatalogDetail CatalogDetail3 { get; set; }
        public virtual Person Person { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogDetail> CatalogDetail4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
