//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSupport.BDContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWListCatalog
    {
        public int IdCatalog { get; set; }
        public string IdTable { get; set; }
        public string TableDesc { get; set; }
        public int IdCatalogDetail { get; set; }
        public string IdTableDetail { get; set; }
        public string DetailDesc { get; set; }
        public bool DetailStatus { get; set; }
    }
}
